### ISSUE TITLE
outdated packer DO validation scripts

### ISSUE THREAD

**Issue by pachamaltese** [digitalocean/marketplace-partners#128]
the packer folder has an outdated validation script that returns false negatives
```
    digitalocean: DigitalOcean Marketplace Image Validation Tool v. 0.1
    digitalocean: Checking local system for Marketplace compatibility...
    digitalocean:
    digitalocean: Distribution: Ubuntu
    digitalocean: Version: 20.04
    digitalocean:
    digitalocean: [PASS] Supported Operating System Detected: Ubuntu
    digitalocean: [FAIL] Ubuntu 20.04 is not a supported Operating System Version
    digitalocean: [PASS] Cloud-init is installed.
    digitalocean: [PASS] Firewall service (ufw) is active
```
