### ISSUE TITLE
Image check failed: DigitalOcean directory detected

### ISSUE THREAD

**Issue by gustavosbarreto** [digitalocean/marketplace-partners#166]
## Output log:

```
digitalocean:
    digitalocean:
    digitalocean: Checking all user-created accounts...
    digitalocean:
    digitalocean:
    digitalocean: Checking the root account...
    digitalocean: [PASS] User root has no password set.
    digitalocean: [ OK ] User root has no SSH keys present
    digitalocean: [PASS] root's Bash History appears to have been cleared
    digitalocean: [FAIL] DigitalOcean directory detected.
    digitalocean: To uninstall the agent and remove the DO directory: 'sudo apt-get purge droplet-agent'
    digitalocean:
    digitalocean:
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: Scan Complete.
    digitalocean: One or more tests failed.  Please review these items and re-test.
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: 7 Tests PASSED
    digitalocean: 2 WARNINGS
    digitalocean: 1 Tests FAILED
    digitalocean: ---------------------------------------------------------------------------------------------------
 ```
 
 ## Steps to reproduce:
 
 ```
 git clone https://github.com/digitalocean/marketplace-partners.git
 export DIGITALOCEAN_TOKEN=...
 packer build marketplace-image.json
 ```
 
 ## What is expected?
 
 A successfully build.
 
 ## Extra information:
 
Since this PR #156 the build seems to fail.
