### ISSUE TITLE
img_check.sh succeeds even when security updates are available

### ISSUE THREAD

**Issue by ximon18** [digitalocean/marketplace-partners#94]
[This issue](https://superuser.com/questions/1496529/sudo-apt-get-update-couldnt-create-temporary-file) causes `apt-get update` in `cleanup.sh` and `img_check.sh` to fail, yet the scripts continue with the end result that the exit code can be zero and the following output is shown:

```
    do: [PASS] There are no pending security updates for this image.
    do:
    do:
    do: Checking for log files in /var/log
    do:
    do:
    do:
    do: Checking all user-created accounts...
    do:
    do:
    do: Checking the root account...
    do: [PASS] User root has no password set.
    do: [ OK ] User root has no SSH keys present
    do: [PASS] root's Bash History appears to have been cleared
    do: [PASS] DigitalOcean Monitoring agent was not found
    do: [PASS] MongoDB is not installed
    do:
    do: ---------------------------------------------------------------------------------------------------
    do: Scan Complete.
    do: All Tests Passed!
    do: ---------------------------------------------------------------------------------------------------
    do: 8 Tests PASSED
    do: 0 WARNINGS
    do: 0 Tests FAILED
    do: ---------------------------------------------------------------------------------------------------
    do: We did not detect any issues with this image. Please be sure to manually ensure that all software installed on the base system is functional, secure and properly configured (or facilities for configuration on first-boot have been created).
```

Yet submission to the vendor portal was rejected with:

```
As part of that review process, when I ran the img_check.sh(https://raw.githubusercontent.com/digitalocean/marketplace-partners/master/scripts/img_check.sh) script it mentioned that the image needs a security update:

[FAIL] There are 1 security updates available for this image that have not been installed.
Here is a list of the security updates that are not installed:
apport
```
